### ISSUE TITLE
Break on_response to two hooks

### ISSUE THREAD

**Issue by dzervas** [operatorequals/wormnest#2]
Currently on_response implements two functionalities: File descriptor manipulation and HTTP response manipulation.

It is best to split the two functionalities in two hooks ('pre_open' and 'pre_response'?)

**Comment by operatorequals** [comment]
Latest Tag `0.5.1` contains 3 hooks for all requests:

`pre_process` : Just after the `IP_WHITELIST` check finishes. Useful for hooks like `User-Agent` HTTP header checking. See `hooks/os_dependent_serve.py`, that changes the URL alias depending on the Requests UA.
The return value of this should be a *behaviour*, like `miss`, or `redir`. If return value is `None`, the processing of the HTTP Request continues.

`pre_file`: Before trying to resolve the URL alias' corresponding file path to a real file. This returns
a [`file` object](https://docs.python.org/3/glossary.html#term-file-object), or [equivalent object](https://docs.python.org/3/library/io.html#module-io), given that it ends up in a Flask's `send_file` call.

`pre_response`: This last one is fired just before the HTTP Response is served. It works with all responses, FIle attachments, `404 Not Found`, `302 Moved`, etc.
Close to the `Flask.after_request` decorator, it is used to manipulate response headers, but depending to *Wormnest* specific logic, e.g.: Return `Server: Apache 2.4` for `.py` downloads and `Server: IIS 8.5` for `.hta` downloads.
